[build]
builder = "nixpacks"
buildCommand = "echo 'Using pre-built frontend'"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm run init-db && npm start"

[healthchecks]
path = "/health"
interval = "10s"
timeout = "5s"
grace_period = "20s" 