[build]
builder = "nixpacks"
nixpacksVersion = "1.11.0"

[deploy]
healthcheck_path = "/health"
healthcheck_timeout_seconds = 100
healthcheck_interval_seconds = 15
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install && cd backend && npm install"]

[start]
cmd = "npm run init-db && npm start"

[healthchecks]
path = "/health"
interval = "10s"
timeout = "5s"
grace_period = "20s" 